TEMPLATE_DIR: C:/Users/rewolinskija/Documents/umls-source-release-1/umls.nlm.nih.gov/releasedocs/templates
OUTPUT_DIR: C:/Users/rewolinskija/Documents/umls-source-release-1/umls.nlm.nih.gov/releasedocs/output
INCLUDE_DIR: C:/Users/rewolinskija/Documents/umls-source-release-1/umls.nlm.nih.gov/releasedocs/testing
RELEASE_VERSION: 2025AA
